name: rag-chatbot-env

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pytorch=2.6.0
  - datasets=4.4.1
  - transformers=4.57.1
  - accelerate==1.11.0
  - sentence-transformers=5.0.0
  - faiss-cpu=1.9.0
  - openai==2.13
  - gradio==5.49.1
  - matplotlib=3.10
  - jupyter=1.1
  - pip
